package com.nadeem.apkscope.core.risk

/** Every rule's [RiskRule.id] (item 11) — stable identifiers, listed in one place so persistence/versioning code and tests have a single source of truth for "what rule IDs can this engine version produce". */
object RuleIds {
 const val ACCESSIBILITY_SERVICE = "STATIC_ACCESSIBILITY_SERVICE"
 const val OVERLAY_PERMISSION = "STATIC_OVERLAY_PERMISSION"
 const val READ_SMS = "STATIC_READ_SMS"
 const val RECEIVE_SMS = "STATIC_RECEIVE_SMS"
 const val SEND_SMS = "STATIC_SEND_SMS"
 const val REQUEST_INSTALL_PACKAGES = "STATIC_REQUEST_INSTALL_PACKAGES"
 const val BOOT_RECEIVER = "STATIC_BOOT_RECEIVER"
 const val BACKGROUND_LOCATION = "STATIC_BACKGROUND_LOCATION"
 const val QUERY_ALL_PACKAGES = "STATIC_QUERY_ALL_PACKAGES"
 const val NATIVE_LIBRARIES_PRESENT = "STATIC_NATIVE_LIBRARIES_PRESENT"
 const val DEBUGGABLE_APK = "STATIC_DEBUGGABLE_APK"
 const val OLD_TARGET_SDK = "STATIC_OLD_TARGET_SDK"
 const val SIGNATURE_VERIFICATION_FAILED = "STATIC_SIGNATURE_VERIFICATION_FAILED"
 const val MANY_EXPORTED_COMPONENTS = "STATIC_MANY_EXPORTED_COMPONENTS"

 const val ACCESSIBILITY_OVERLAY_COMBINATION = "STATIC_ACCESSIBILITY_OVERLAY_COMBINATION"
 const val ACCESSIBILITY_BOOT_COMBINATION = "STATIC_ACCESSIBILITY_BOOT_COMBINATION"
 const val SMS_INTERNET_COMBINATION = "STATIC_SMS_INTERNET_COMBINATION"
 const val CONTACTS_INTERNET_COMBINATION = "STATIC_CONTACTS_INTERNET_COMBINATION"
 const val BACKGROUND_LOCATION_INTERNET_COMBINATION = "STATIC_BACKGROUND_LOCATION_INTERNET_COMBINATION"

 // Runtime rules (runtime-v1)
 const val RUNTIME_NETWORK_ACTIVITY = "RUNTIME_NETWORK_ACTIVITY"
 const val RUNTIME_RAW_IP_CONNECTION = "RUNTIME_RAW_IP_CONNECTION"
 const val RUNTIME_POLICY_DENIED_DESTINATION = "RUNTIME_POLICY_DENIED_DESTINATION"
 const val RUNTIME_HIGH_OUTBOUND_DATA = "RUNTIME_HIGH_OUTBOUND_DATA"
 const val RUNTIME_MANY_DISTINCT_DESTINATIONS = "RUNTIME_MANY_DISTINCT_DESTINATIONS"
 const val RUNTIME_DNS_ACTIVITY = "RUNTIME_DNS_ACTIVITY"

 // Combined rules (combined-v1)
 const val COMBINED_CONTACTS_NETWORK = "COMBINED_CONTACTS_NETWORK"
 const val COMBINED_SMS_NETWORK = "COMBINED_SMS_NETWORK"
 const val COMBINED_LOCATION_NETWORK = "COMBINED_LOCATION_NETWORK"
 const val COMBINED_ACCESSIBILITY_NETWORK = "COMBINED_ACCESSIBILITY_NETWORK"
 const val COMBINED_ACCESSIBILITY_OVERLAY_NETWORK = "COMBINED_ACCESSIBILITY_OVERLAY_NETWORK"
 const val COMBINED_BOOT_PERSISTENCE_NETWORK = "COMBINED_BOOT_PERSISTENCE_NETWORK"
 const val COMBINED_INSTALL_PACKAGES_NETWORK = "COMBINED_INSTALL_PACKAGES_NETWORK"
 const val COMBINED_SENSITIVE_CAPABILITY_PRIVATE_DESTINATION = "COMBINED_SENSITIVE_CAPABILITY_PRIVATE_DESTINATION"
}

const val RUNTIME_ENGINE_VERSION = "runtime-v1"
const val COMBINED_ENGINE_VERSION = "combined-v1"

