#!/usr/bin/env bash
#
# Compile FridaLoaderFactory.java into app/src/main/assets/frida_loader.dex.
#
# The Frida-mode patch pipeline (ReVancedApkRepacker) sets the target APK's
# android:appComponentFactory to com.nadeem.apkscope.FridaLoaderFactory and
# injects this dex as the next classesN.dex. The factory loads the Frida gadget
# (System.loadLibrary("gadget")) before the app's own Application is created, so
# SSL_read/SSL_write hooks are in place from process start.
#
# frida_loader.dex is a checked-in asset (peer of the frida-gadget-*.so files),
# not a Gradle build output, so it must be regenerated by hand whenever
# FridaLoaderFactory.java changes. Requires JDK 17 and the Android SDK
# build-tools' d8. Override ANDROID_HOME / BUILD_TOOLS / ANDROID_JAR / JAVA_HOME
# if autodetection does not fit your machine.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="$repo_root/FridaLoaderFactory.java"
out="$repo_root/app/src/main/assets/frida_loader.dex"

ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
[ -d "$ANDROID_HOME" ] || ANDROID_HOME="$HOME/Library/Android"

pick_latest() { ls -1 "$1" 2>/dev/null | sort -V | tail -1; }
BUILD_TOOLS="${BUILD_TOOLS:-$ANDROID_HOME/build-tools/$(pick_latest "$ANDROID_HOME/build-tools")}"
ANDROID_JAR="${ANDROID_JAR:-$ANDROID_HOME/platforms/$(pick_latest "$ANDROID_HOME/platforms")/android.jar}"
JAVAC="${JAVA_HOME:+$JAVA_HOME/bin/}javac"

[ -f "$src" ] || { echo "missing $src" >&2; exit 1; }
[ -x "$BUILD_TOOLS/d8" ] || { echo "d8 not found under $BUILD_TOOLS" >&2; exit 1; }
[ -f "$ANDROID_JAR" ] || { echo "android.jar not found at $ANDROID_JAR" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "javac  -> $work"
"$JAVAC" -source 8 -target 8 -bootclasspath "$ANDROID_JAR" -d "$work" "$src"

echo "d8     -> $out"
"$BUILD_TOOLS/d8" --min-api 30 --output "$work" \
  "$work/com/nadeem/apkscope/FridaLoaderFactory.class"
cp "$work/classes.dex" "$out"

echo "wrote $out ($(wc -c <"$out") bytes)"
